apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-profile
  namespace: default
spec:
  selector:
    matchLabels:
      app: mysql-profile
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-profile
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword"
        - name: MYSQL_DATABASE
          value: "profiledb"
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-profile
  namespace: default
spec:
  selector:
    app: mysql-profile
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP

